# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aee6459ad30cde266955347d98c7dc17bd1f30193aaab007e682845a56361a1c8e278ccf5406b7e8f4bf4d4c9f5a0a097b7bb9960600a8fb20cb9bf9f97bc34

test:
  secret_key_base: 46360d96929e512b665ebb3bde6461f807d3a07e3d33d850947bf1be3f415b5bdc333db6cfbb91cdeef7aa3027c1e5cfa71520dfe4b7389299e1caf9b80de20b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
